[Variables]
;------------------------
;   INITIALIZE COLORS
;------------------------
RGBA=150,150,150,100
R=0
G=0
B=0
A=255
H=0
S=0
V=0
HexColor=#DD6B3A
ColorTooltip=Цвет фона События для 4-го календаря

;------------------------
;     SKIN SETTINGS
;------------------------
Version=1.0.1
ColorThemePath=#ROOTCONFIGPATH#/@Resources/Variables_Theme_Dark.ini
CSN=#Cal_4_Bg#
OldColor=0,150,255,255
IBG=48,48,48,255
IBO=110,110,110,255
INVA=200,90,90,255
CO=190,190,190
Active=1
CPCursor=0
Tooltip=1
Scale=0
PosX=446
PosY=100
Hotkey=1
Menu=1
Mini=0
SHIFT=0
INC1=1
INC2=1
INC3=1
INCZ=10
LP=0
CP=0
Mini=(1-#Mini#)
HSV=#HSV#
PickButtonX=2751
PickButtonY=491
RGB=216,111,55,255




